In [32]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score

In [30]:
#pip install matplotlib


In [33]:
#pip install scikit-learn

## CIFAR-10
## 10 Classe, 6000 per class, 60K Images

![Cifar10](images/vlcsnap-2024-09-15-17h40m46s514.png)





In [3]:
import torch
import torchvision
import torchvision.transforms as transforms
import torch.nn as nn

In [4]:
# Transform variable
# Compose allows us to add an arrayof different transformations
transform = transforms.Compose([

    # trainset dataset(below) to tensor
    transforms.ToTensor(),

    # normalization: Every pixel 0-255, divide by 255, to get values between 0 and 255
    # But here - from [0, 1] to [-1, 1]
    # parameters - means, SD and apply it for each channels - RGB - 3 channels
    transforms.Normalize(
        (0.5, 0.5, 0.5), # mean for each channels, since range is from 0 to 1
        (0.5, 0.5, 0.5), # SD for each channels
    )

])

In [5]:
# Load Dataset - Train
trainset = torchvision.datasets.CIFAR10(
    root = "./data", # download the dataset in the directory 'data'
    download = True, 
    train = True,
    #We need to transform everything to tensor
    transform = transform
)

Files already downloaded and verified


In [6]:
batch_size = 128
# We will add mini batch SD
# We can create dataloader in PyTorch - to convert it to mini batches

trainLoader = torch.utils.data.DataLoader(
    trainset,
    batch_size = batch_size,
    shuffle = True, 
    num_workers = 2, # Different jobs*
)

In [7]:
# See how the dataloader looks like
# Iterate through trainLoader

for data in trainLoader:
    # data[0] - image
    # data[1] - label
    print(data[1])

    # To check the batch size 
    print(data[0].shape) # 128 images and each image (3 - Chennels, 32 - Height, 32 - Width)
    # Each pixel contains between -1 to 1 because of normalization
   

tensor([5, 0, 2, 3, 9, 0, 0, 7, 2, 6, 9, 1, 8, 4, 1, 1, 8, 5, 6, 3, 4, 3, 6, 8,
        1, 7, 2, 0, 9, 0, 6, 1, 8, 1, 0, 9, 8, 7, 2, 0, 7, 0, 7, 9, 2, 7, 4, 9,
        0, 0, 8, 3, 3, 8, 4, 4, 7, 7, 0, 4, 0, 5, 6, 8, 6, 7, 6, 4, 8, 9, 4, 9,
        8, 1, 0, 9, 1, 7, 5, 6, 9, 4, 1, 6, 7, 6, 0, 8, 8, 0, 8, 8, 7, 9, 3, 3,
        7, 4, 0, 5, 6, 3, 9, 0, 5, 9, 2, 2, 0, 0, 3, 8, 9, 8, 1, 2, 4, 4, 3, 7,
        6, 4, 1, 9, 1, 4, 7, 9])
torch.Size([128, 3, 32, 32])
tensor([2, 7, 5, 1, 3, 3, 0, 1, 8, 1, 0, 5, 0, 0, 9, 8, 4, 5, 8, 7, 2, 6, 5, 8,
        5, 0, 3, 7, 1, 1, 2, 8, 4, 3, 5, 2, 4, 1, 3, 0, 3, 3, 7, 2, 6, 4, 1, 1,
        7, 9, 6, 0, 8, 6, 3, 8, 4, 3, 4, 9, 8, 5, 5, 9, 0, 3, 4, 5, 4, 3, 6, 7,
        0, 0, 6, 0, 9, 3, 9, 4, 2, 5, 4, 9, 1, 7, 4, 8, 7, 4, 9, 5, 8, 4, 8, 8,
        2, 0, 2, 4, 7, 7, 2, 0, 4, 5, 6, 1, 2, 2, 2, 9, 2, 9, 6, 5, 7, 4, 7, 1,
        8, 0, 6, 0, 3, 1, 7, 5])
torch.Size([128, 3, 32, 32])
tensor([6, 9, 4, 1, 7, 6, 3, 9, 2, 5, 1, 9, 6, 9, 8, 8, 6, 4, 9, 8, 5, 2, 0,

In [8]:
# For test dataset
testValidSet = torchvision.datasets.CIFAR10(
    root = "./data", # download the dataset in the directory 'data'
    download = True, 
    train = False,
    #We need to transform everything to tensor
    transform = transform
)

Files already downloaded and verified


In [9]:
# Split testValidSet dataset
validSet, testSet = torch.utils.data.random_split(
    testValidSet,
    (5000, 5000)
)

In [10]:
 # Create valid DataLoader
validLoader = torch.utils.data.DataLoader(
    validSet,
    batch_size = batch_size,
    shuffle = False,
    num_workers = 2
)

In [11]:
for data in validLoader:
    print(data[0].shape)

torch.Size([128, 3, 32, 32])
torch.Size([128, 3, 32, 32])
torch.Size([128, 3, 32, 32])
torch.Size([128, 3, 32, 32])
torch.Size([128, 3, 32, 32])
torch.Size([128, 3, 32, 32])
torch.Size([128, 3, 32, 32])
torch.Size([128, 3, 32, 32])
torch.Size([128, 3, 32, 32])
torch.Size([128, 3, 32, 32])
torch.Size([128, 3, 32, 32])
torch.Size([128, 3, 32, 32])
torch.Size([128, 3, 32, 32])
torch.Size([128, 3, 32, 32])
torch.Size([128, 3, 32, 32])
torch.Size([128, 3, 32, 32])
torch.Size([128, 3, 32, 32])
torch.Size([128, 3, 32, 32])
torch.Size([128, 3, 32, 32])
torch.Size([128, 3, 32, 32])
torch.Size([128, 3, 32, 32])
torch.Size([128, 3, 32, 32])
torch.Size([128, 3, 32, 32])
torch.Size([128, 3, 32, 32])
torch.Size([128, 3, 32, 32])
torch.Size([128, 3, 32, 32])
torch.Size([128, 3, 32, 32])
torch.Size([128, 3, 32, 32])
torch.Size([128, 3, 32, 32])
torch.Size([128, 3, 32, 32])
torch.Size([128, 3, 32, 32])
torch.Size([128, 3, 32, 32])
torch.Size([128, 3, 32, 32])
torch.Size([128, 3, 32, 32])
torch.Size([12

In [12]:
# Test Loader
testLoader = torch.utils.data.DataLoader(
    testSet,
    batch_size = batch_size,
    shuffle = False, 
    num_workers = 2
)

In [13]:
for data in testLoader:
    print(data[0].shape)

torch.Size([128, 3, 32, 32])
torch.Size([128, 3, 32, 32])
torch.Size([128, 3, 32, 32])
torch.Size([128, 3, 32, 32])
torch.Size([128, 3, 32, 32])
torch.Size([128, 3, 32, 32])
torch.Size([128, 3, 32, 32])
torch.Size([128, 3, 32, 32])
torch.Size([128, 3, 32, 32])
torch.Size([128, 3, 32, 32])
torch.Size([128, 3, 32, 32])
torch.Size([128, 3, 32, 32])
torch.Size([128, 3, 32, 32])
torch.Size([128, 3, 32, 32])
torch.Size([128, 3, 32, 32])
torch.Size([128, 3, 32, 32])
torch.Size([128, 3, 32, 32])
torch.Size([128, 3, 32, 32])
torch.Size([128, 3, 32, 32])
torch.Size([128, 3, 32, 32])
torch.Size([128, 3, 32, 32])
torch.Size([128, 3, 32, 32])
torch.Size([128, 3, 32, 32])
torch.Size([128, 3, 32, 32])
torch.Size([128, 3, 32, 32])
torch.Size([128, 3, 32, 32])
torch.Size([128, 3, 32, 32])
torch.Size([128, 3, 32, 32])
torch.Size([128, 3, 32, 32])
torch.Size([128, 3, 32, 32])
torch.Size([128, 3, 32, 32])
torch.Size([128, 3, 32, 32])
torch.Size([128, 3, 32, 32])
torch.Size([128, 3, 32, 32])
torch.Size([12

In [14]:
# Set Classes

classes = [
    "plane",
    "car",
    "bird",
    "cat",
    "deer",
    "dog",
    "frog",
    "horse",
    "ship",
    "truck"

]

## Visualize Data

In [15]:
# Function to Display Image

def imgShow(img):

    # Unnormalize from [-1, 1] to [0, 1]
    img = img / 2 + 0.5

    # Convert to Numpy
    img = img.numpy()

    # transpose
    # from [channels, height, width] = [height, width, channels]
    imgTransposed = np.transpose(img, (1, 2, 0))

    # Plot image
    plt.imshow(imgTransposed)

    plt.show()

In [16]:
# Iter function - call iter method on iterable object
dataIter = iter(trainLoader)


# Get first element on iterable
# Each item in the iterable is batch, 1 batch contain 128 different images

images, labels = dataIter.__next__()

print(images.shape)



torch.Size([128, 3, 32, 32])


In [17]:
# Select image

imageIdx = 0

# Show Image

imgShow(images[imageIdx])
print(classes[labels[imageIdx]]) #Its a number

print(images[imageIdx].shape)

<IPython.core.display.Javascript object>

ship
torch.Size([3, 32, 32])


## Defining the Neural Network

In [18]:
# Define model
# init: define layers
# forward: data flows through the model

class CNN(nn.Module):

    # Define init method
    def __init__(self, hidden_layer = 100):
        super().__init__()


        # Conv 1
        # input channels, output channels(feature map)/ no. of filters(6 diff. filters), kernel/filter size
        # 6 filters and this filters has different parameters(we need to update this weights)
        self.conv1 = nn.Conv2d(3, 6, 5)

        # Pooling Layer
        # kernel size, stride
        # No parameter updation
        self.pool = nn.MaxPool2d(2, 2)

        # Flatten

        # Fully connected layer
        # input dimension(we select 10 arbitarily), output dimension
        # The input image was 32x32 but due to Conv2D and MaxPool2D it has different and lower dimensions
        self.fc1 = nn.Linear(1176, hidden_layer) #1st parameter - After Pooling

        #Output layer
        #Output dimension 10 - because 10 outputs
        self.out = nn.Linear(hidden_layer, 10)


        # For Convolution layer and Fully connected layer we have ReLU activation

        # activation function
        self.act = nn.ReLU()


    # Define forward method
    def forward(self, x):

        # Print the shape of the input data
        #print('Inside Forward, before conv1: ', x.shape)

        # Convolution 1
        # For each feature map we need to add activation function
        x = self.act(self.conv1(x))
        
        # Different dimension because of feature map
        #print('After conv1: ', x.shape)

        # Pooling layer
        x = self.pool(x)

        #print('After Pooling(Pooling for 6 diff. feature map): ', x.shape)


        # Flattening
        # [batch size, multiplication of dimensions]
        # view - change the shape only
        x = x.view(-1, 6*14*14) # 2nd parameter - After Pooling

        #print(x.shape) # Now we know the input to the Fully Connected Layer


        # Fc1
        x = self.act(self.fc1(x))

        #print(x.shape)


        # Output Layer

        x = self.out(x)


        #print(x.shape)

        # Return Output
        return x

        



In [19]:
# Define Model

model = CNN() 

print(model)

CNN(
  (conv1): Conv2d(3, 6, kernel_size=(5, 5), stride=(1, 1))
  (pool): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  (fc1): Linear(in_features=1176, out_features=100, bias=True)
  (out): Linear(in_features=100, out_features=10, bias=True)
  (act): ReLU()
)


In [20]:
# Call Iter method
dataIter = iter(trainLoader)

# Get first item
images, labels = dataIter.__next__()

#print(images.shape)

# Pass mini batch to forward pass of model
test = model.forward(images)

print("Image shape - output from Model: ", model.forward(images).shape)

print(test)


Image shape - output from Model:  torch.Size([128, 10])
tensor([[ 0.0871,  0.0359, -0.1200,  ..., -0.0524,  0.0636, -0.1341],
        [ 0.0948,  0.0552, -0.1074,  ..., -0.1048,  0.0611, -0.0380],
        [ 0.0619,  0.0811, -0.1110,  ..., -0.0297,  0.0985, -0.1232],
        ...,
        [ 0.0438,  0.0625, -0.0806,  ..., -0.0180,  0.0948, -0.0911],
        [ 0.0544,  0.0597, -0.1132,  ..., -0.0951,  0.0234, -0.1163],
        [ 0.0865,  0.0922, -0.1187,  ..., -0.0799,  0.0534, -0.1093]],
       grad_fn=<AddmmBackward0>)


In [21]:
print(test.shape)

torch.Size([128, 10])


## Define Cost Function and Optimizer

In [22]:
# Cost function
costFunction = nn.CrossEntropyLoss()

# Optimizer(to update parameters), for self.conv1
optimizer = torch.optim.Adam(model.parameters(), lr = 0.001)


## Train Model - Train dataset

![Training](images/nn_training.png)

In [34]:
epochs = 10

# train loss array
trainLossArray = np.zeros(shape = (epochs))

# Create plot
fig, ax = plt.subplots(1, 2, figsize = (10, 3))

# Iterate on Epochs
for i in range(epochs):
    
    print(f"Epoch {i}")

    # Plot loss function for entire dataset instead of each mini batch
    epoch_train_loss = 0


    # TRAINING
    # Iterate on batches of the training dataset
    for tmp in trainLoader:
        #tmp[0] is the image data
        #tmp[1] is the label

        #print(tmp[0].shape)

        data = tmp[0]
        label = tmp[1]

        # Get model predictions
        prediction = model.forward(data)

        #print(prediction.shape) # Shape of the mini batch, dimension should be 10 for each class


        # With the labels and predictions - we will get the cost function
        loss = costFunction(prediction, label) # This loss will be for each mini batch

        #print(loss)
        # Step 1: Get the Cost Value
        # Step 2: Get gradient value, backpropagation
        # Step 3: Update Parameters

        # We need to add IMPORTANT
        # PyTorch by default save and restore the value of the end of the gradient
        # We need absolute value not accumulative, To stop the accumulation of the gradient values
        # And to get unique value for each mini batch, set to zero for gradient 

        # gradient to zero
        optimizer.zero_grad()

        # Compute gradient value using backpropagation
        loss.backward()

        # Update the parameters  - Adam
        # Step method will take gradient from loss value and update the parameters using Adam
        optimizer.step()

        # Sum loss values
        epoch_train_loss += loss.item() 

    # add loss value of the itteration
    #trainLossArray[i] = epoch_train_loss / 50000 # Average loss
    
    print("Train loss: ", epoch_train_loss / 50000 )

    # Validation

    epoch_valid_loss = 0

    metric_valid = 0

    batch_counter = 0
    
    for tmp in validLoader:

        labelsVal = tmp[1]
        dataVal = tmp[0]

        # get predictions
        predictionsVal = model.forward(dataVal)

        # get cost function value

        lossVal = costFunction(predictionsVal, labelsVal)

        epoch_valid_loss = lossVal.item()

        batch_counter += 1

    print("Valid loss: ", epoch_valid_loss / 50000 )


    # Compute metric value in mini batch
    metric_valid += accuracy_score(
         
         # True values
         labelsVal,

         # Prediction Values
         torch.argmax(predictionsVal, 1).detach().numpy()
    )
    

    print("Metric Valid", metric_valid/batch_counter)
    # PLOT

    # ax[0].plot(trainLossArray[0:i], c = "red")

    # fig.canvas.draw()



<IPython.core.display.Javascript object>

Epoch 0
Train loss:  0.0058735262203216555
Valid loss:  2.2281718254089355e-05
Metric Valid 0.015625
Epoch 1
Train loss:  0.0056601914876699445
Valid loss:  1.934881567955017e-05
Metric Valid 0.01875
Epoch 2
Train loss:  0.005483639006018639
Valid loss:  1.7593837976455687e-05
Metric Valid 0.01875
Epoch 3
Train loss:  0.005316205010414124
Valid loss:  1.6684330701828004e-05
Metric Valid 0.021875
Epoch 4
Train loss:  0.005159020947813988
Valid loss:  2.1075072288513182e-05
Metric Valid 0.01875
Epoch 5
Train loss:  0.004996102888584137
Valid loss:  1.8429213762283325e-05
Metric Valid 0.01875
Epoch 6
Train loss:  0.004847770879268646
Valid loss:  1.579110026359558e-05
Metric Valid 0.021875
Epoch 7
Train loss:  0.004711990997195244
Valid loss:  2.0727732181549073e-05
Metric Valid 0.021875
Epoch 8
Train loss:  0.004536701757311821
Valid loss:  1.829604148864746e-05
Metric Valid 0.015625
Epoch 9
Train loss:  0.004392528594732285
Valid loss:  1.7124853134155274e-05
Metric Valid 0.01875


## Test Dataset and Get Metrics

In [35]:
for tmp in testLoader:


    data = tmp[0]
    labels = tmp[1]

    predictions = model.forward(data)


    print(predictions.shape)

torch.Size([128, 10])
torch.Size([128, 10])
torch.Size([128, 10])
torch.Size([128, 10])
torch.Size([128, 10])
torch.Size([128, 10])
torch.Size([128, 10])
torch.Size([128, 10])
torch.Size([128, 10])
torch.Size([128, 10])
torch.Size([128, 10])
torch.Size([128, 10])
torch.Size([128, 10])
torch.Size([128, 10])
torch.Size([128, 10])
torch.Size([128, 10])
torch.Size([128, 10])
torch.Size([128, 10])
torch.Size([128, 10])
torch.Size([128, 10])
torch.Size([128, 10])
torch.Size([128, 10])
torch.Size([128, 10])
torch.Size([128, 10])
torch.Size([128, 10])
torch.Size([128, 10])
torch.Size([128, 10])
torch.Size([128, 10])
torch.Size([128, 10])
torch.Size([128, 10])
torch.Size([128, 10])
torch.Size([128, 10])
torch.Size([128, 10])
torch.Size([128, 10])
torch.Size([128, 10])
torch.Size([128, 10])
torch.Size([128, 10])
torch.Size([128, 10])
torch.Size([128, 10])
torch.Size([8, 10])
